"""cria a tabela de candidatos

Revision ID: 460b27ebd863
Revises: 
Create Date: 2024-04-21 23:49:41.001102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460b27ebd863'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidato', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contato', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contato')
    )
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidato_candidato'), ['candidato'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidato_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidato_email'))
        batch_op.drop_index(batch_op.f('ix_candidato_candidato'))

    op.drop_table('candidato')
    # ### end Alembic commands ###
