"""Adiciona a coluna de contato

Revision ID: 6cf141b22d86
Revises: e81b23507caf
Create Date: 2024-04-21 19:17:40.743247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf141b22d86'
down_revision = 'e81b23507caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contato', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['contato'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('contato')

    # ### end Alembic commands ###
