"""tabela de candidatos

Revision ID: e81b23507caf
Revises: 
Create Date: 2024-04-21 16:32:42.443959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e81b23507caf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidato', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidato_candidato'), ['candidato'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidato_email'), ['email'], unique=True)

    op.drop_table('Concorrentes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Concorrentes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_completo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('sexo', mysql.ENUM('Feminino', 'Masculino', 'Outro'), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('objetivo', mysql.TEXT(), nullable=False),
    sa.Column('formacao_academica', mysql.TEXT(), nullable=False),
    sa.Column('experiencia_profissional', mysql.TEXT(), nullable=False),
    sa.Column('data_envio', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    with op.batch_alter_table('candidato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidato_email'))
        batch_op.drop_index(batch_op.f('ix_candidato_candidato'))

    op.drop_table('candidato')
    # ### end Alembic commands ###
